version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=newsteam

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: newsteam
    ports:
      - "3307:3307"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: