version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app # Monte le dossier local dans le conteneur
      - /app/node_modules # Empêche les conflits avec les modules node

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=mongodb
      - DB_NAME=newsteam
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app # Monte le dossier local dans le conteneur
      - /app/node_modules # Empêche les conflits avec les modules node

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: